exercises_data = [

    # ══════════════════════════════════════════════════════════════════
    #  PECHO
    # ══════════════════════════════════════════════════════════════════
    ('Press de Banca con Barra (agarre medio)', 'Pecho'),
    ('Press de Banca con Barra (agarre ancho)', 'Pecho'),
    ('Press de Banca con Mancuernas', 'Pecho'),
    ('Press de Banca con Mancuernas (agarre neutro)', 'Pecho'),
    ('Press Inclinado con Barra', 'Pecho'),
    ('Press Inclinado con Mancuernas', 'Pecho'),
    ('Press Inclinado con Mancuernas (agarre neutro)', 'Pecho'),
    ('Press Declinado con Barra', 'Pecho'),
    ('Press Declinado con Mancuernas', 'Pecho'),
    ('Press de Banca en Máquina', 'Pecho'),
    ('Press Inclinado en Máquina', 'Pecho'),
    ('Press Declinado en Máquina', 'Pecho'),
    ('Press de Banca en Smith', 'Pecho'),
    ('Press Inclinado en Smith', 'Pecho'),
    ('Press Declinado en Smith', 'Pecho'),
    ('Press de Banca con Cadenas', 'Pecho'),
    ('Press de Banca con Bandas Elásticas', 'Pecho'),
    ('Press de Banca con Agarre Cerrado', 'Pecho'),
    ('Press de Banca con Agarre Invertido', 'Pecho'),
    ('Press Guillotine con Barra', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Plano', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Inclinado', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Declinado', 'Pecho'),
    ('Cruce de Poleas (polea alta)', 'Pecho'),
    ('Cruce de Poleas (polea baja)', 'Pecho'),
    ('Cruce de Poleas a Un Brazo', 'Pecho'),
    ('Press de Pecho en Polea (de pie)', 'Pecho'),
    ('Press de Pecho en Polea Inclinada', 'Pecho'),
    ('Pullover con Mancuerna', 'Pecho'),
    ('Pullover con Barra Curvada', 'Pecho'),
    ('Pullover en Polea Alta', 'Pecho'),
    ('Fondos en Paralelas (versión pecho)', 'Pecho'),
    ('Flexiones de Brazos (estándar)', 'Pecho'),
    ('Flexiones con Agarre Ancho', 'Pecho'),
    ('Flexiones con Agarre Cerrado', 'Pecho'),
    ('Flexiones con Pies Elevados', 'Pecho'),
    ('Flexiones Declinadas', 'Pecho'),
    ('Flexiones Inclinadas', 'Pecho'),
    ('Flexiones a Una Mano', 'Pecho'),
    ('Flexiones con Palmada', 'Pecho'),
    ('Flexiones sobre Mancuernas', 'Pecho'),
    ('Flexiones en Suspension (TRX)', 'Pecho'),
    ('Press de Pecho con Pelota Medicinal', 'Pecho'),

    # ══════════════════════════════════════════════════════════════════
    #  ESPALDA
    # ══════════════════════════════════════════════════════════════════
    ('Peso Muerto con Barra', 'Espalda'),
    ('Peso Muerto Sumo', 'Espalda'),
    ('Peso Muerto en Déficit con Barra', 'Espalda'),
    ('Peso Muerto en Rack (parcial)', 'Espalda'),
    ('Peso Muerto con Barra Hexagonal', 'Espalda'),
    ('Peso Muerto con Cadenas', 'Espalda'),
    ('Peso Muerto con Bandas Elásticas', 'Espalda'),
    ('Peso Muerto Sumo con Bandas Elásticas', 'Espalda'),
    ('Peso Muerto en Smith', 'Espalda'),
    ('Remo con Barra Inclinado (agarre prono)', 'Espalda'),
    ('Remo con Barra Inclinado (agarre supino)', 'Espalda'),
    ('Remo con Barra a Una Mano', 'Espalda'),
    ('Remo con Barra en T', 'Espalda'),
    ('Remo con Mancuerna a Una Mano en Banco', 'Espalda'),
    ('Remo en Polea Baja Sentado (agarre cerrado)', 'Espalda'),
    ('Remo en Polea Baja Sentado (agarre ancho)', 'Espalda'),
    ('Remo en Polea Baja a Un Brazo', 'Espalda'),
    ('Remo en Polea Alta Sentado', 'Espalda'),
    ('Remo en Máquina (Leverage Row)', 'Espalda'),
    ('Remo en Smith', 'Espalda'),
    ('Remo en Suspension (TRX)', 'Espalda'),
    ('Remo Invertido con Barra', 'Espalda'),
    ('Jalón al Pecho con Agarre Ancho', 'Espalda'),
    ('Jalón al Pecho con Agarre Cerrado', 'Espalda'),
    ('Jalón al Pecho con Agarre Neutro', 'Espalda'),
    ('Jalón al Pecho con Agarre Inverso', 'Espalda'),
    ('Jalón Detrás del Cuello', 'Espalda'),
    ('Jalón a Una Mano en Polea', 'Espalda'),
    ('Jalón Recto con Polea Alta (Pullover en Polea)', 'Espalda'),
    ('Dominadas con Agarre Prono (ancho)', 'Espalda'),
    ('Dominadas con Agarre Prono (cerrado)', 'Espalda'),
    ('Dominadas con Agarre Supino (Chin-Up)', 'Espalda'),
    ('Dominadas con Agarre Neutro', 'Espalda'),
    ('Dominadas con Lastre', 'Espalda'),
    ('Dominadas Asistidas con Banda Elástica', 'Espalda'),
    ('Dominadas Asistidas en Máquina', 'Espalda'),
    ('Encogimientos con Barra (trapecios)', 'Espalda'),
    ('Encogimientos con Mancuernas', 'Espalda'),
    ('Encogimientos en Máquina', 'Espalda'),
    ('Encogimientos con Barra Detrás del Cuerpo', 'Espalda'),
    ('Encogimientos en Smith', 'Espalda'),
    ('Hiperextensiones en Banco (lumbar)', 'Espalda'),
    ('Hiperextensiones Inversas en Banco', 'Isquios'),
    ('Buenos Días con Barra', 'Espalda'),
    ('Buenos Días Sentado con Barra', 'Espalda'),
    ('Buenos Días con Banda Elástica', 'Espalda'),
    ('Remo de Cuello en Polea Baja', 'Espalda'),
    ('Jalón Recto con Barra de Tríceps en Polea', 'Espalda'),
    ('Remo Elevado en Polea Alta', 'Espalda'),
    ('Remo de Trineo', 'Espalda'),

    # ══════════════════════════════════════════════════════════════════
    #  HOMBRO
    # ══════════════════════════════════════════════════════════════════
    ('Press Militar con Barra de Pie', 'Hombro'),
    ('Press Militar con Barra Sentado', 'Hombro'),
    ('Press Militar Detrás del Cuello con Barra (sentado)', 'Hombro'),
    ('Press Arnold con Mancuernas', 'Hombro'),
    ('Press de Hombros con Mancuernas (sentado)', 'Hombro'),
    ('Press de Hombros con Mancuernas (de pie)', 'Hombro'),
    ('Press de Hombros en Máquina', 'Hombro'),
    ('Press de Hombros en Polea', 'Hombro'),
    ('Press de Hombros con Banda Elástica', 'Hombro'),
    ('Press Push con Barra (impulso con piernas)', 'Hombro'),
    ('Press Bradford con Barra', 'Hombro'),
    ('Press de Hombros con Kettlebell a Una Mano', 'Hombro'),
    ('Press de Hombros con Kettlebells (bilateral)', 'Hombro'),
    ('Elevaciones Laterales con Mancuernas', 'Hombro'),
    ('Elevaciones Laterales en Polea Baja', 'Hombro'),
    ('Elevaciones Laterales con Banda Elástica', 'Hombro'),
    ('Elevaciones Laterales Sentado', 'Hombro'),
    ('Elevaciones Laterales Apoyado en Banco Inclinado', 'Hombro'),
    ('Elevaciones Frontales con Mancuernas', 'Hombro'),
    ('Elevaciones Frontales con Disco', 'Hombro'),
    ('Elevaciones Frontales con Barra', 'Hombro'),
    ('Elevaciones Frontales en Polea', 'Hombro'),
    ('Elevaciones Frontales Alternas con Mancuernas', 'Hombro'),
    ('Elevaciones de Deltoides Posterior Inclinado (mancuernas)', 'Hombro'),
    ('Elevaciones de Deltoides Posterior Sentado', 'Hombro'),
    ('Elevaciones de Deltoides Posterior en Máquina', 'Hombro'),
    ('Elevaciones de Deltoides Posterior en Polea', 'Hombro'),
    ('Remo Vertical con Barra', 'Hombro'),
    ('Remo Vertical con Mancuernas', 'Hombro'),
    ('Remo Vertical en Polea Baja', 'Hombro'),
    ('Remo Vertical a Una Mano con Mancuerna', 'Hombro'),
    ('Face Pull en Polea (deltoides posterior)', 'Hombro'),
    ('Rotación Externa con Mancuerna (deltoides)', 'Hombro'),
    ('Rotación Interna con Banda Elástica', 'Hombro'),
    ('Rotación Externa con Banda Elástica', 'Hombro'),
    ('Encogimientos con Mancuernas en Máquina de Gemelos (trapecios)', 'Hombro'),

    # ══════════════════════════════════════════════════════════════════
    #  BICEPS
    # ══════════════════════════════════════════════════════════════════
    ('Curl de Biceps con Barra (agarre supino)', 'Biceps'),
    ('Curl de Biceps con Barra (agarre cerrado)', 'Biceps'),
    ('Curl de Biceps con Barra EZ', 'Biceps'),
    ('Curl de Biceps con Mancuernas Simultáneo', 'Biceps'),
    ('Curl de Biceps con Mancuernas Alterno', 'Biceps'),
    ('Curl Martillo con Mancuernas (bilateral)', 'Biceps'),
    ('Curl Martillo con Mancuernas Alterno', 'Biceps'),
    ('Curl Martillo Cruzado con Mancuerna', 'Biceps'),
    ('Curl en Banco Scott con Barra', 'Biceps'),
    ('Curl en Banco Scott con Barra EZ', 'Biceps'),
    ('Curl en Banco Scott con Mancuerna (a una mano)', 'Biceps'),
    ('Curl en Banco Scott en Máquina', 'Biceps'),
    ('Curl de Concentración con Mancuerna', 'Biceps'),
    ('Curl en Polea Baja con Barra', 'Biceps'),
    ('Curl en Polea Baja con Cuerda', 'Biceps'),
    ('Curl en Polea Alta a Dos Brazos', 'Biceps'),
    ('Curl en Polea a Una Mano de Pie', 'Biceps'),
    ('Curl Inverso con Barra', 'Biceps'),
    ('Curl Inverso con Barra EZ', 'Biceps'),
    ('Curl Inverso en Polea', 'Biceps'),
    ('Curl de Muñeca con Barra (agarre supino)', 'Biceps'),
    ('Curl de Muñeca con Barra (agarre prono)', 'Biceps'),
    ('Curl Inclinado con Mancuernas', 'Biceps'),
    ('Curl Spider con Mancuernas en Banco Inclinado', 'Biceps'),
    ('Curl Drag con Barra', 'Biceps'),
    ('Curl Zottman con Mancuernas', 'Biceps'),
    ('Curl con Banda Elástica', 'Biceps'),
    ('Curl de Biceps a Una Mano en Banco Scott con Polea', 'Biceps'),
    ('Curl de Biceps Tumbado en Polea Alta', 'Biceps'),
    ('Curl 21 con Barra', 'Biceps'),

    # ══════════════════════════════════════════════════════════════════
    #  TRICEPS
    # ══════════════════════════════════════════════════════════════════
    ('Extensión de Tríceps en Polea Alta con Barra Recta', 'Triceps'),
    ('Extensión de Tríceps en Polea Alta con Barra V', 'Triceps'),
    ('Extensión de Tríceps en Polea Alta con Cuerda', 'Triceps'),
    ('Extensión de Tríceps en Polea Alta con Agarre Inverso', 'Triceps'),
    ('Extensión de Tríceps sobre la Cabeza en Polea (cuerda)', 'Triceps'),
    ('Extensión de Tríceps sobre la Cabeza con Mancuerna (bilateral)', 'Triceps'),
    ('Extensión de Tríceps sobre la Cabeza con Mancuerna (a una mano)', 'Triceps'),
    ('Extensión de Tríceps sobre la Cabeza con Barra', 'Triceps'),
    ('Extensión de Tríceps sobre la Cabeza con Barra EZ', 'Triceps'),
    ('Press Francés con Barra (tendido sobre banco)', 'Triceps'),
    ('Press Francés con Barra EZ (tendido sobre banco)', 'Triceps'),
    ('Press Francés con Mancuernas (tendido sobre banco)', 'Triceps'),
    ('Press Francés Declinado con Barra', 'Triceps'),
    ('Patada de Tríceps con Mancuerna (inclinado)', 'Triceps'),
    ('Patada de Tríceps en Polea Baja', 'Triceps'),
    ('Fondos en Paralelas (versión tríceps)', 'Triceps'),
    ('Fondos en Banco (Dips en banco)', 'Triceps'),
    ('Fondos en Banco con Lastre', 'Triceps'),
    ('Fondos en Anillas', 'Triceps'),
    ('Extensión de Tríceps Tumbado en Polea Baja', 'Triceps'),
    ('Extensión de Tríceps a Una Mano en Polea', 'Triceps'),
    ('Extensión de Tríceps en Polea Inclinada', 'Triceps'),
    ('Press de Banca con Agarre Cerrado en Banco Plano', 'Triceps'),
    ('Press de Banca con Agarre Cerrado en Banco Inclinado', 'Triceps'),
    ('Máquina de Tríceps (press hacia abajo)', 'Triceps'),
    ('Máquina de Dipeo de Tríceps', 'Triceps'),
    ('Extensión de Tríceps con Banda Elástica sobre la Cabeza', 'Triceps'),
    ('Extensión de Tríceps con Banda Elástica en Polea', 'Triceps'),
    ('Press Tate con Mancuernas', 'Triceps'),
    ('Press JM con Barra', 'Triceps'),

    # ══════════════════════════════════════════════════════════════════
    #  PIERNA — CUADRICEPS
    # ══════════════════════════════════════════════════════════════════
    ('Sentadilla con Barra Trasera', 'Pierna'),
    ('Sentadilla con Barra Trasera (postura ancha)', 'Pierna'),
    ('Sentadilla con Barra Frontal (agarre limpio)', 'Pierna'),
    ('Sentadilla Frontal con Agarre Cruzado', 'Pierna'),
    ('Sentadilla Olímpica con Barra', 'Pierna'),
    ('Sentadilla Sumo con Barra', 'Pierna'),
    ('Sentadilla Hack con Barra', 'Pierna'),
    ('Sentadilla Hack en Máquina', 'Pierna'),
    ('Sentadilla en Smith', 'Pierna'),
    ('Sentadilla con Mancuernas', 'Pierna'),
    ('Sentadilla Goblet con Mancuerna', 'Pierna'),
    ('Sentadilla Goblet con Kettlebell', 'Pierna'),
    ('Sentadilla con Bandas Elásticas', 'Pierna'),
    ('Sentadilla con Cadenas', 'Pierna'),
    ('Sentadilla Box con Barra (hasta cajón)', 'Pierna'),
    ('Sentadilla Box con Bandas Elásticas', 'Pierna'),
    ('Sentadilla Búlgara con Mancuernas', 'Pierna'),
    ('Sentadilla Búlgara en Smith', 'Pierna'),
    ('Sentadilla Búlgara a Una Pierna con Mancuerna', 'Pierna'),
    ('Sentadilla Pistol (a una pierna)', 'Pierna'),
    ('Sentadilla Pistol en Smith', 'Pierna'),
    ('Sentadilla Jefferson con Barra', 'Pierna'),
    ('Sentadilla Zercher con Barra', 'Pierna'),
    ('Sentadilla Sissy (cuádriceps)', 'Pierna'),
    ('Sentadilla Sissy con Lastre', 'Pierna'),
    ('Sentadilla a Una Pierna con Barra', 'Pierna'),
    ('Sentadilla Suspendida en TRX', 'Pierna'),
    ('Prensa de Piernas 45 Grados', 'Pierna'),
    ('Prensa de Piernas Vertical en Smith', 'Pierna'),
    ('Prensa de Piernas con Postura Cerrada (cuádriceps)', 'Pierna'),
    ('Prensa de Piernas a Una Pierna', 'Pierna'),
    ('Prensa de Piernas con Postura Ancha', 'Pierna'),
    ('Extensión de Cuádriceps en Máquina', 'Pierna'),
    ('Extensión de Cuádriceps a Una Pierna en Máquina', 'Pierna'),
    ('Zancada con Barra', 'Pierna'),
    ('Zancada con Mancuernas', 'Pierna'),
    ('Zancada Caminando con Mancuernas', 'Pierna'),
    ('Zancada Caminando con Barra', 'Pierna'),
    ('Zancada Inversa con Mancuernas', 'Pierna'),
    ('Zancada Lateral con Mancuernas', 'Pierna'),
    ('Subida al Cajón con Mancuernas', 'Pierna'),
    ('Subida al Cajón con Barra', 'Pierna'),
    ('Subida al Cajón con Elevación de Rodilla', 'Pierna'),
    ('Prensa Inclinada de Piernas (pierna delantera)', 'Pierna'),

    # ══════════════════════════════════════════════════════════════════
    #  ISQUIOS Y GLUTEO
    # ══════════════════════════════════════════════════════════════════
    ('Curl Femoral Tumbado en Máquina', 'Isquios'),
    ('Curl Femoral Sentado en Máquina', 'Isquios'),
    ('Curl Femoral de Pie en Máquina', 'Isquios'),
    ('Curl Femoral con Banda Elástica Sentado', 'Isquios'),
    ('Curl Femoral en Fitball', 'Isquios'),
    ('Curl Nórdico (isquios)', 'Isquios'),
    ('Curl de Isquios Manual en Suelo', 'Isquios'),
    ('Peso Muerto Rumano con Barra', 'Isquios'),
    ('Peso Muerto Rumano con Mancuernas', 'Isquios'),
    ('Peso Muerto Rumano a Una Pierna con Mancuerna', 'Isquios'),
    ('Peso Muerto con Piernas Rígidas con Barra', 'Isquios'),
    ('Peso Muerto con Piernas Rígidas con Mancuernas', 'Isquios'),
    ('Peso Muerto Sumo con Mancuerna (foco glúteo)', 'Isquios'),
    ('Puente de Glúteos con Barra (Hip Thrust en banco)', 'Isquios'),
    ('Puente de Glúteos en Suelo con Barra', 'Isquios'),
    ('Puente de Glúteos a Una Pierna con Barra', 'Isquios'),
    ('Puente de Glúteos en Suelo con Pie Elevado', 'Isquios'),
    ('Puente de Glúteos con Banda Elástica', 'Isquios'),
    ('Patada de Glúteos en Polea (de pie)', 'Isquios'),
    ('Patada de Glúteos en Cuadrupedia', 'Isquios'),
    ('Patada de Glúteos en Máquina', 'Isquios'),
    ('Hip Thrust en Máquina', 'Isquios'),
    ('Abducción de Cadera en Máquina (sentado)', 'Isquios'),
    ('Abducción de Cadera en Polea Baja', 'Isquios'),
    ('Aducción de Cadera en Máquina (sentado)', 'Isquios'),
    ('Aducción de Cadera en Polea Baja', 'Isquios'),
    ('Elevación de Pierna Lateral de Pie con Banda', 'Isquios'),
    ('Sentadilla con Paso Lateral con Banda', 'Isquios'),
    ('Hiperextension Inversa en Banco', 'Isquios'),
    ('Patada de Glúteos hacia Atrás con Banda', 'Isquios'),

    # ══════════════════════════════════════════════════════════════════
    #  GEMELOS
    # ══════════════════════════════════════════════════════════════════
    ('Elevación de Talones de Pie en Máquina', 'Gemelos'),
    ('Elevación de Talones Sentado en Máquina', 'Gemelos'),
    ('Elevación de Talones en Prensa de Piernas', 'Gemelos'),
    ('Elevación de Talones con Mancuernas (de pie)', 'Gemelos'),
    ('Elevación de Talones con Barra (de pie)', 'Gemelos'),
    ('Elevación de Talones a Una Pierna con Mancuerna', 'Gemelos'),
    ('Elevación de Talones en Smith', 'Gemelos'),
    ('Elevación de Talones en Burro con Compañero', 'Gemelos'),
    ('Elevación de Talones Inversa (tibial anterior)', 'Gemelos'),
    ('Elevación de Talones con Peso Corporal (de pie)', 'Gemelos'),
    ('Elevación de Talones en Cajón (rango completo)', 'Gemelos'),
    ('Elevación de Talones Explosiva (salto de puntillas)', 'Gemelos'),

    # ══════════════════════════════════════════════════════════════════
    #  CORE — ABDOMINALES Y LUMBAR
    # ══════════════════════════════════════════════════════════════════
    ('Crunch Abdominal en Suelo', 'Core'),
    ('Crunch en Máquina', 'Core'),
    ('Crunch en Polea Alta con Cuerda', 'Core'),
    ('Crunch Cruzado en Suelo (oblicuos)', 'Core'),
    ('Crunch Cruzado en Polea Alta', 'Core'),
    ('Crunch Inverso en Suelo', 'Core'),
    ('Crunch Inverso Colgado en Barra', 'Core'),
    ('Crunch en Fitball', 'Core'),
    ('Crunch Declinado en Banco', 'Core'),
    ('Crunch Declinado con Giro (oblicuos)', 'Core'),
    ('Crunch en Suelo con Manos sobre la Cabeza', 'Core'),
    ('Plancha Frontal (isométrico)', 'Core'),
    ('Plancha Lateral (oblicuos)', 'Core'),
    ('Plancha Frontal con Desplazamiento de Pies', 'Core'),
    ('Plancha Frontal con Toque de Hombros', 'Core'),
    ('Plancha con Elevación Alterna de Brazo y Pierna', 'Core'),
    ('Elevación de Piernas Tumbado en Banco', 'Core'),
    ('Elevación de Piernas Tumbado en Suelo', 'Core'),
    ('Elevación de Rodillas Colgado en Barra', 'Core'),
    ('Elevación de Piernas Colgado en Barra', 'Core'),
    ('Elevación de Piernas en Paralelas', 'Core'),
    ('Tijeras en Suelo', 'Core'),
    ('Patada de Bicicleta en Suelo (bicicleta abdominal)', 'Core'),
    ('Abdominal Completo en Suelo', 'Core'),
    ('Abdominal Completo con Banda Elástica', 'Core'),
    ('Abdominal Jackknife (navaja)', 'Core'),
    ('Rodillo Abdominal de Pie', 'Core'),
    ('Rodillo Abdominal de Rodillas', 'Core'),
    ('Rodillo con Barra (rollout)', 'Core'),
    ('Giro Ruso con Disco', 'Core'),
    ('Giro Ruso con Mancuerna', 'Core'),
    ('Giro de Cable de Pie (hacha de leñador)', 'Core'),
    ('Giro de Cable Diagonal hacia Abajo', 'Core'),
    ('Bandera del Dragón (Dragon Flag)', 'Core'),
    ('Superman en Suelo (lumbar)', 'Core'),
    ('Vacío Abdominal de Pie', 'Core'),
    ('Escalador (subida de montaña)', 'Core'),
    ('Escalador con Pausa', 'Core'),
    ('Puente Abdominal en Fitball', 'Core'),
    ('Curl Posterior con Fitball (isquios y core)', 'Core'),
    ('Levantamiento Turco con Kettlebell', 'Core'),
    ('Puñetazo con Cable (anti-rotación de core)', 'Core'),

    # ══════════════════════════════════════════════════════════════════
    #  COMPUESTO — MOVIMIENTOS OLIMPICOS Y FUNCIONALES
    # ══════════════════════════════════════════════════════════════════
    ('Cargada y Jerk Completo (Clean & Jerk)', 'Compuesto'),
    ('Cargada de Potencia (Power Clean)', 'Compuesto'),
    ('Cargada desde Colgado (Hang Clean)', 'Compuesto'),
    ('Cargada desde Cajón (Clean desde Bloques)', 'Compuesto'),
    ('Arrancada Completa (Snatch)', 'Compuesto'),
    ('Arrancada de Potencia (Power Snatch)', 'Compuesto'),
    ('Arrancada desde Colgado (Hang Snatch)', 'Compuesto'),
    ('Push Jerk con Barra', 'Compuesto'),
    ('Split Jerk con Barra', 'Compuesto'),
    ('Thruster con Barra', 'Compuesto'),
    ('Thruster con Mancuernas', 'Compuesto'),
    ('Thruster con Kettlebell', 'Compuesto'),
    ('Swing con Kettlebell a Dos Manos', 'Compuesto'),
    ('Swing con Kettlebell a Una Mano', 'Compuesto'),
    ('Clean con Kettlebell a Una Mano', 'Compuesto'),
    ('Snatch con Kettlebell a Una Mano', 'Compuesto'),
    ('Press con Kettlebell sobre la Cabeza a Una Mano', 'Compuesto'),
    ('Windmill con Kettlebell', 'Compuesto'),
    ('Clean con Mancuernas', 'Compuesto'),
    ('Muscle-Up en Barra (dorsales y tríceps)', 'Compuesto'),
    ('Muscle-Up en Anillas', 'Compuesto'),
    ('Fondos en Anillas', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal al Pecho', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal sobre la Cabeza', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal de Costado', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal en Slam', 'Compuesto'),
    ('Salto al Cajón (Box Jump)', 'Compuesto'),
    ('Salto Lateral al Cajón', 'Compuesto'),
    ('Salto con Sentadilla (Jump Squat con Barra)', 'Compuesto'),
    ('Salto de Tijera (Split Jump)', 'Compuesto'),
    ('Salto de Rodillas en Suelo', 'Compuesto'),
    ('Volteo de Neumático (Tire Flip)', 'Compuesto'),
    ('Acarreo del Granjero (Farmers Walk)', 'Compuesto'),
    ('Acarreo Contralateral (maleta y sobrecabeza)', 'Compuesto'),
    ('Empuje de Trineo (Sled Push)', 'Compuesto'),
    ('Arrastre de Trineo hacia Atrás', 'Compuesto'),
    ('Escalada de Cuerda', 'Compuesto'),
    ('Balanceo de Cuerdas de Batalla', 'Compuesto'),
    ('Cargada de Piedra de Atlas', 'Compuesto'),
    ('Clean con Barra y Empuje (Clean & Press)', 'Compuesto'),
    ('Arrancada de Halterofilia con Barra', 'Compuesto'),
    ('Despegue de Cargada con Barra (Clean Deadlift)', 'Compuesto'),

    # ══════════════════════════════════════════════════════════════════
    #  CARDIO
    # ══════════════════════════════════════════════════════════════════
    ('Carrera Continua en Cinta', 'Cardio'),
    ('Carrera por Intervalos en Cinta (HIIT)', 'Cardio'),
    ('Carrera al Aire Libre', 'Cardio'),
    ('Sprint de 100 Metros', 'Cardio'),
    ('Sprint de 200 Metros', 'Cardio'),
    ('Bicicleta Estática a Ritmo Continuo', 'Cardio'),
    ('Bicicleta Estática por Intervalos (HIIT)', 'Cardio'),
    ('Bicicleta de Montaña', 'Cardio'),
    ('Remo en Máquina Estática', 'Cardio'),
    ('Elíptica a Ritmo Continuo', 'Cardio'),
    ('Escaladora (Stairmaster)', 'Cardio'),
    ('Natación (crol)', 'Cardio'),
    ('Saltar a la Comba (continuo)', 'Cardio'),
    ('Saltar a la Comba por Intervalos', 'Cardio'),
    ('Burpees', 'Cardio'),
    ('Caminata Inclinada en Cinta (treadmill walk 12-3-30)', 'Cardio'),
    ('Caminata con Seguro en Terreno', 'Cardio'),
    ('Salto de Estrella (Jumping Jacks)', 'Cardio'),
    ('Esquí Nórdico Estático', 'Cardio'),
]