exercises_data = [
    # ── PECHO ──────────────────────────────────────────────────────────────────
    ('Press de Banca con Barra (Agarre Medio)', 'Pecho'),
    ('Press de Banca con Mancuernas', 'Pecho'),
    ('Press de Banca Inclinado con Barra', 'Pecho'),
    ('Press de Banca Inclinado con Mancuernas', 'Pecho'),
    ('Press de Banca Declinado con Barra', 'Pecho'),
    ('Press de Banca Declinado con Mancuernas', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Plano', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Inclinado', 'Pecho'),
    ('Aperturas con Mancuernas en Banco Declinado', 'Pecho'),
    ('Press de Banca en Máquina', 'Pecho'),
    ('Press Inclinado en Máquina', 'Pecho'),
    ('Press Declinado en Smith', 'Pecho'),
    ('Press Inclinado en Smith', 'Pecho'),
    ('Press de Banca en Smith', 'Pecho'),
    ('Press con Agarre Cerrado en Banca Plana', 'Pecho'),
    ('Aperturas en Polea Alta (Cruce de Poleas)', 'Pecho'),
    ('Aperturas en Polea Baja', 'Pecho'),
    ('Press de Pecho en Polea Baja (de pie)', 'Pecho'),
    ('Press de Pecho en Polea Inclinada', 'Pecho'),
    ('Pullover con Mancuerna', 'Pecho'),
    ('Pullover con Barra Curvada', 'Pecho'),
    ('Fondos en Paralelas (versión pecho)', 'Pecho'),
    ('Flexiones de Brazos (estándar)', 'Pecho'),
    ('Flexiones con Agarre Amplio', 'Pecho'),
    ('Flexiones con Pies Elevados', 'Pecho'),
    ('Flexiones Declinadas', 'Pecho'),
    ('Flexiones Inclinadas', 'Pecho'),
    ('Press de Pecho con Bandas Elásticas', 'Pecho'),
    ('Press Guillotine con Barra', 'Pecho'),
    ('Press de Banca con Cadenas', 'Pecho'),
    ('Press de Banca con Agarre Invertido', 'Pecho'),

    # ── ESPALDA ────────────────────────────────────────────────────────────────
    ('Peso Muerto con Barra', 'Espalda'),
    ('Peso Muerto Rumano con Barra', 'Espalda'),
    ('Peso Muerto Rumano con Mancuernas', 'Espalda'),
    ('Peso Muerto Sumo', 'Espalda'),
    ('Peso Muerto en Déficit', 'Espalda'),
    ('Peso Muerto con Barra Trap', 'Espalda'),
    ('Peso Muerto en Rack (Rack Pulls)', 'Espalda'),
    ('Remo con Barra Inclinado', 'Espalda'),
    ('Remo con Mancuerna a Una Mano', 'Espalda'),
    ('Remo en Polea Baja Sentado', 'Espalda'),
    ('Remo en Polea Alta Sentado con Agarre Cerrado', 'Espalda'),
    ('Remo en T con Barra', 'Espalda'),
    ('Remo en Smith', 'Espalda'),
    ('Jalón al Pecho en Polea Alta (Agarre Ancho)', 'Espalda'),
    ('Jalón al Pecho en Polea Alta (Agarre Cerrado)', 'Espalda'),
    ('Jalón al Pecho en Polea Alta (Agarre Neutro)', 'Espalda'),
    ('Jalón Frontal a Una Mano', 'Espalda'),
    ('Jalón Detrás del Cuello', 'Espalda'),
    ('Dominadas Agarre Prono (Pull-Up)', 'Espalda'),
    ('Dominadas Agarre Supino (Chin-Up)', 'Espalda'),
    ('Dominadas con Agarre Neutro', 'Espalda'),
    ('Dominadas con Lastre', 'Espalda'),
    ('Dominadas Asistidas con Banda', 'Espalda'),
    ('Remo Invertido con Barra', 'Espalda'),
    ('Remo en Suspensión (TRX)', 'Espalda'),
    ('Pullover Recto con Polea Alta', 'Espalda'),
    ('Encogimientos con Barra (Trapecios)', 'Espalda'),
    ('Encogimientos con Mancuernas', 'Espalda'),
    ('Encogimientos en Máquina', 'Espalda'),
    ('Hiperextensiones de Espalda', 'Espalda'),
    ('Buenos Días con Barra', 'Espalda'),
    ('Remo con Banda Elástica', 'Espalda'),
    ('Face Pull en Polea', 'Espalda'),
    ('Remo de Cuello en Polea Baja', 'Espalda'),

    # ── HOMBRO ─────────────────────────────────────────────────────────────────
    ('Press Militar con Barra (de pie)', 'Hombro'),
    ('Press Militar con Barra (sentado)', 'Hombro'),
    ('Press Arnold con Mancuernas', 'Hombro'),
    ('Press de Hombros con Mancuernas (sentado)', 'Hombro'),
    ('Press de Hombros con Mancuernas (de pie)', 'Hombro'),
    ('Press de Hombros en Máquina', 'Hombro'),
    ('Press de Hombros en Polea', 'Hombro'),
    ('Press Militar Detrás del Cuello con Barra', 'Hombro'),
    ('Elevaciones Laterales con Mancuernas', 'Hombro'),
    ('Elevaciones Laterales en Polea Baja', 'Hombro'),
    ('Elevaciones Laterales con Banda', 'Hombro'),
    ('Elevaciones Laterales Sentado', 'Hombro'),
    ('Elevaciones Frontales con Mancuernas', 'Hombro'),
    ('Elevaciones Frontales con Disco', 'Hombro'),
    ('Elevaciones Frontales con Barra', 'Hombro'),
    ('Elevaciones Frontales en Polea', 'Hombro'),
    ('Elevaciones de Deltoides Posterior Inclinado', 'Hombro'),
    ('Elevaciones de Deltoides Posterior Sentado', 'Hombro'),
    ('Elevaciones de Deltoides Posterior en Máquina', 'Hombro'),
    ('Remo Vertical con Barra', 'Hombro'),
    ('Remo Vertical con Mancuernas', 'Hombro'),
    ('Remo Vertical en Polea', 'Hombro'),
    ('Rotación Externa con Mancuerna', 'Hombro'),
    ('Rotación Interna con Banda', 'Hombro'),
    ('Press Push (impulso con piernas)', 'Hombro'),
    ('Press Bradford con Barra', 'Hombro'),

    # ── BÍCEPS ─────────────────────────────────────────────────────────────────
    ('Curl de Bíceps con Barra', 'Bíceps'),
    ('Curl de Bíceps con Mancuernas Alterno', 'Bíceps'),
    ('Curl de Bíceps con Mancuernas Simultáneo', 'Bíceps'),
    ('Curl Martillo con Mancuernas', 'Bíceps'),
    ('Curl Martillo Cruzado', 'Bíceps'),
    ('Curl en Banco Scott con Barra', 'Bíceps'),
    ('Curl en Banco Scott con Mancuerna a Una Mano', 'Bíceps'),
    ('Curl en Banco Scott en Máquina', 'Bíceps'),
    ('Curl con Barra EZ', 'Bíceps'),
    ('Curl de Concentración con Mancuerna', 'Bíceps'),
    ('Curl en Polea Baja', 'Bíceps'),
    ('Curl en Polea Alta (Cable)', 'Bíceps'),
    ('Curl en Polea Baja con Cuerda', 'Bíceps'),
    ('Curl Inverso con Barra', 'Bíceps'),
    ('Curl Inverso con Barra EZ', 'Bíceps'),
    ('Curl de Muñeca con Barra (agarre supino)', 'Bíceps'),
    ('Curl de Muñeca con Barra (agarre prono)', 'Bíceps'),
    ('Curl Inclinado con Mancuernas', 'Bíceps'),
    ('Curl Spider con Mancuernas', 'Bíceps'),
    ('Curl Drag con Barra', 'Bíceps'),
    ('Curl con Banda Elástica', 'Bíceps'),
    ('Curl Zottman con Mancuernas', 'Bíceps'),

    # ── TRÍCEPS ────────────────────────────────────────────────────────────────
    ('Extensión de Tríceps con Polea Alta (cuerda)', 'Tríceps'),
    ('Extensión de Tríceps con Polea Alta (barra)', 'Tríceps'),
    ('Extensión de Tríceps con Polea Alta (V-Bar)', 'Tríceps'),
    ('Extensión de Tríceps con Polea Alta Agarre Inverso', 'Tríceps'),
    ('Extensión de Tríceps sobre la Cabeza en Polea', 'Tríceps'),
    ('Extensión de Tríceps sobre la Cabeza con Mancuerna', 'Tríceps'),
    ('Extensión de Tríceps sobre la Cabeza con Barra', 'Tríceps'),
    ('Press Francés con Barra (Skull Crusher)', 'Tríceps'),
    ('Press Francés con Barra EZ', 'Tríceps'),
    ('Press Francés con Mancuernas', 'Tríceps'),
    ('Patada de Tríceps con Mancuerna', 'Tríceps'),
    ('Fondos en Paralelas (versión tríceps)', 'Tríceps'),
    ('Fondos en Banco', 'Tríceps'),
    ('Fondos en Banco con Lastre', 'Tríceps'),
    ('Extensión de Tríceps Tumbado en Polea', 'Tríceps'),
    ('Extensión de Tríceps a Una Mano en Polea', 'Tríceps'),
    ('Extensión de Tríceps en Polea Inclinada', 'Tríceps'),
    ('Press Cerrado con Barra en Banco Plano', 'Tríceps'),
    ('Press Cerrado con Mancuernas', 'Tríceps'),
    ('Extensión de Tríceps con Banda Elástica', 'Tríceps'),
    ('Máquina de Tríceps (extensión)', 'Tríceps'),

    # ── PIERNA / CUÁDRICEPS ────────────────────────────────────────────────────
    ('Sentadilla con Barra (trasera)', 'Pierna'),
    ('Sentadilla con Barra (frontal)', 'Pierna'),
    ('Sentadilla Sumo con Barra', 'Pierna'),
    ('Sentadilla en Smith', 'Pierna'),
    ('Sentadilla Hack con Barra', 'Pierna'),
    ('Sentadilla Hack en Máquina', 'Pierna'),
    ('Sentadilla con Mancuernas', 'Pierna'),
    ('Sentadilla Goblet con Mancuerna', 'Pierna'),
    ('Sentadilla con Bandas Elásticas', 'Pierna'),
    ('Sentadilla con Cadenas', 'Pierna'),
    ('Sentadilla Box (hasta cajón)', 'Pierna'),
    ('Sentadilla Búlgara (Split Squat) con Mancuernas', 'Pierna'),
    ('Sentadilla Búlgara en Smith', 'Pierna'),
    ('Sentadilla Pistol (a una pierna)', 'Pierna'),
    ('Sentadilla Pistol en Smith', 'Pierna'),
    ('Sentadilla Jefferson', 'Pierna'),
    ('Sentadilla Zercher', 'Pierna'),
    ('Prensa de Piernas (Leg Press 45°)', 'Pierna'),
    ('Prensa de Piernas Vertical en Smith', 'Pierna'),
    ('Prensa de Piernas con Pie Cerrado', 'Pierna'),
    ('Prensa de Piernas a Una Pierna', 'Pierna'),
    ('Extensión de Cuádriceps en Máquina', 'Pierna'),
    ('Extensión de Cuádriceps a Una Pierna', 'Pierna'),
    ('Zancada con Barra', 'Pierna'),
    ('Zancada con Mancuernas', 'Pierna'),
    ('Zancada Caminando con Mancuernas', 'Pierna'),
    ('Zancada Caminando con Barra', 'Pierna'),
    ('Zancada Elevada (de pie) con Mancuernas', 'Pierna'),
    ('Subida al Cajón con Mancuernas', 'Pierna'),
    ('Subida al Cajón con Barra', 'Pierna'),
    ('Sentadilla Olímpica', 'Pierna'),

    # ── ISQUIOS / GLÚTEO ───────────────────────────────────────────────────────
    ('Curl Femoral Tumbado en Máquina', 'Isquios'),
    ('Curl Femoral Sentado en Máquina', 'Isquios'),
    ('Curl Femoral de pie en Máquina', 'Isquios'),
    ('Curl Femoral con Banda Elástica Sentado', 'Isquios'),
    ('Curl Femoral en Fitball', 'Isquios'),
    ('Peso Muerto Rumano con Barra (foco isquios)', 'Isquios'),
    ('Peso Muerto con Piernas Rígidas con Barra', 'Isquios'),
    ('Peso Muerto con Piernas Rígidas con Mancuernas', 'Isquios'),
    ('Curl Nórdico (Nordic Hamstring Curl)', 'Isquios'),
    ('Curl de Isquios Manual en Suelo', 'Isquios'),
    ('Puente de Glúteos con Barra (Hip Thrust)', 'Isquios'),
    ('Puente de Glúteos en Banco', 'Isquios'),
    ('Puente de Glúteos a Una Pierna', 'Isquios'),
    ('Elevación de Cadera en Suelo con Barra', 'Isquios'),
    ('Patada de Glúteos en Polea (de pie)', 'Isquios'),
    ('Patada de Glúteos en Cuadrupedia', 'Isquios'),
    ('Abducción de Cadera en Máquina', 'Isquios'),
    ('Aducción de Cadera en Máquina', 'Isquios'),
    ('Hiperextensión Inversa en Banco', 'Isquios'),
    ('Good Morning Sentado con Barra', 'Isquios'),

    # ── GEMELOS ────────────────────────────────────────────────────────────────
    ('Elevación de Talones de pie (Máquina)', 'Gemelos'),
    ('Elevación de Talones Sentado (Máquina)', 'Gemelos'),
    ('Elevación de Talones con Mancuernas', 'Gemelos'),
    ('Elevación de Talones con Barra', 'Gemelos'),
    ('Elevación de Talones en Prensa de Piernas', 'Gemelos'),
    ('Elevación de Talones a Una Pierna con Mancuerna', 'Gemelos'),
    ('Elevación de Talones en Smith', 'Gemelos'),
    ('Elevación de Talones en Burro (con compañero)', 'Gemelos'),
    ('Elevación de Talones Inversa (tibiales)', 'Gemelos'),

    # ── CORE / ABDOMINALES ─────────────────────────────────────────────────────
    ('Crunch Abdominal en Suelo', 'Core'),
    ('Crunch en Máquina', 'Core'),
    ('Crunch en Polea Alta (con cuerda)', 'Core'),
    ('Crunch Cruzado (oblicuos)', 'Core'),
    ('Crunch Inverso (Reverse Crunch)', 'Core'),
    ('Crunch en Fitball', 'Core'),
    ('Crunch Longitudinal (Tuck Crunch)', 'Core'),
    ('Crunch Declinado', 'Core'),
    ('Crunch Declinado Oblicuo', 'Core'),
    ('Crunch Cruzado en Polea', 'Core'),
    ('Plancha Frontal (Plank)', 'Core'),
    ('Plancha Lateral', 'Core'),
    ('Plancha Frontal con Apoyo en Pelota', 'Core'),
    ('Plancha con Rotación de Cadera', 'Core'),
    ('Elevación de Piernas Tumbado', 'Core'),
    ('Elevación de Piernas Colgado en Barra', 'Core'),
    ('Elevación de Rodillas Colgado en Barra', 'Core'),
    ('Tijeras en Suelo', 'Core'),
    ('Bicicleta en Suelo (Bicycle Crunch)', 'Core'),
    ('Sit-Up Completo en Suelo', 'Core'),
    ('Sit-Up con Banda Elástica', 'Core'),
    ('Sit-Up Jackknife', 'Core'),
    ('Rodillo Abdominal (Ab Wheel)', 'Core'),
    ('Rodillo con Barra (Ab Rollout)', 'Core'),
    ('Russian Twist con Peso', 'Core'),
    ('Dragon Flag (Bandera del Dragón)', 'Core'),
    ('Giro de Cable de pie (Wood Chop)', 'Core'),
    ('Vacío Abdominal (Stomach Vacuum)', 'Core'),
    ('Puente Abdominal con Fitball', 'Core'),
    ('Escalador (Mountain Climber)', 'Core'),
    ('Levantamiento Turco con Kettlebell', 'Core'),

    # ── COMPUESTO / OLÍMPICO ───────────────────────────────────────────────────
    ('Clean y Jerk (Arranque y Cargada)', 'Compuesto'),
    ('Cargada de Potencia (Power Clean)', 'Compuesto'),
    ('Cargada Colgada (Hang Clean)', 'Compuesto'),
    ('Arrancada (Snatch)', 'Compuesto'),
    ('Arrancada de Potencia (Power Snatch)', 'Compuesto'),
    ('Arrancada Colgada (Hang Snatch)', 'Compuesto'),
    ('Push Jerk (Empuje con Flexión)', 'Compuesto'),
    ('Split Jerk (Empuje con Zancada)', 'Compuesto'),
    ('Thruster con Barra', 'Compuesto'),
    ('Thruster con Mancuernas', 'Compuesto'),
    ('Thruster con Kettlebell', 'Compuesto'),
    ('Swing con Kettlebell a Una Mano', 'Compuesto'),
    ('Swing con Kettlebell a Dos Manos', 'Compuesto'),
    ('Clean con Kettlebell a Una Mano', 'Compuesto'),
    ('Press con Kettlebell a Una Mano en Techo', 'Compuesto'),
    ('Snatch con Kettlebell', 'Compuesto'),
    ('Windmill con Kettlebell', 'Compuesto'),
    ('Clean con Mancuerna', 'Compuesto'),
    ('Muscle-Up en Barra', 'Compuesto'),
    ('Muscle-Up en Anillas', 'Compuesto'),
    ('Fondos en Anillas', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal al Pecho', 'Compuesto'),
    ('Lanzamiento de Balón Medicinal Sobre la Cabeza', 'Compuesto'),
    ('Salto al Cajón (Box Jump)', 'Compuesto'),
    ('Salto Lateral al Cajón', 'Compuesto'),
    ('Salto con Sentadilla (Jump Squat)', 'Compuesto'),
    ('Salto de Tijera (Scissors Jump)', 'Compuesto'),
    ('Salto de Rodillas', 'Compuesto'),
    ('Cargada de Barra con Empuje (Clean & Press)', 'Compuesto'),
    ('Volteo de Neumático (Tire Flip)', 'Compuesto'),
    ('Acarreo del Granjero (Farmers Walk)', 'Compuesto'),
    ('Empuje de Trineo (Sled Push)', 'Compuesto'),
    ('Arrastre de Trineo', 'Compuesto'),
    ('Escalada de Cuerda', 'Compuesto'),

    # ── CARDIO ─────────────────────────────────────────────────────────────────
    ('Carrera en Cinta', 'Cardio'),
    ('Carrera por Intervalos (HIIT)', 'Cardio'),
    ('Bicicleta Estática', 'Cardio'),
    ('Bicicleta de Montaña', 'Cardio'),
    ('Remo Estático (Rowing Machine)', 'Cardio'),
    ('Elíptica', 'Cardio'),
    ('Escaladora (Stairmaster)', 'Cardio'),
    ('Piscina / Natación', 'Cardio'),
    ('Saltar a la Comba', 'Cardio'),
    ('Sprints de 100m', 'Cardio'),
    ('Burpees', 'Cardio'),
    ('Caminata en Cinta (con inclinación)', 'Cardio'),
]