import sqlite3
import os

DB_PATH = 'mtfitness.db'

def expand():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # --- EXERCISES (~140 total) ---
    exercises = [
        # PECHO (22)
        ('Press Banca Plano con Barra', 'Pecho'), ('Press Banca Inclinado con Barra', 'Pecho'), 
        ('Press Banca Declinado con Barra', 'Pecho'), ('Press Banca Plano con Mancuernas', 'Pecho'),
        ('Press Banca Inclinado con Mancuernas', 'Pecho'), ('Press Banca Declinado con Mancuernas', 'Pecho'),
        ('Aperturas Planas con Mancuernas', 'Pecho'), ('Aperturas Inclinadas con Mancuernas', 'Pecho'),
        ('Cruces en Polea Alta', 'Pecho'), ('Cruces en Polea Baja', 'Pecho'),
        ('Cruces en Polea a Altura Media', 'Pecho'), ('Peck Deck', 'Pecho'),
        ('Press en Máquina Convergente', 'Pecho'), ('Press Inclinado en Máquina', 'Pecho'),
        ('Fondos en Paralelas (Enfoque Pecho)', 'Pecho'), ('Flexiones de Brazos (Pushups)', 'Pecho'),
        ('Flexiones Inclinadas', 'Pecho'), ('Flexiones Declinadas', 'Pecho'),
        ('Pullover con Mancuerna', 'Pecho'), ('Press de Pecho en Polea', 'Pecho'),
        ('Press Landmine para Pecho', 'Pecho'), ('Flexiones con Palmada', 'Pecho'),

        # ESPALDA (22)
        ('Dominadas Pronas (Anchas)', 'Espalda'), ('Dominadas Supinas (Chin-ups)', 'Espalda'),
        ('Dominadas Neutras', 'Espalda'), ('Jalón al Pecho Abierto', 'Espalda'),
        ('Jalón al Pecho con Agarre Neutro', 'Espalda'), ('Jalón tras Nuca', 'Espalda'),
        ('Remo con Barra Prono', 'Espalda'), ('Remo con Barra Supino', 'Espalda'),
        ('Remo con Mancuerna a una Mano', 'Espalda'), ('Remo Gironda (Polea Baja)', 'Espalda'),
        ('Remo en Punta (Barra T)', 'Espalda'), ('Remo en Máquina (Hammer)', 'Espalda'),
        ('Pull-over en Polea Alta (Brazos Rígidos)', 'Espalda'), ('Peso Muerto Convencional', 'Espalda'),
        ('Peso Muerto Sumo', 'Espalda'), ('Rack Pulls', 'Espalda'),
        ('Hiperextensiones Lumbares', 'Espalda'), ('Good Mornings', 'Espalda'),
        ('Face Pull (Enfoque Espalda Alta)', 'Espalda'), ('Remo Pendlay', 'Espalda'),
        ('Remo con Mancuernas en Banco Inclinado', 'Espalda'), ('Remo en TRX', 'Espalda'),

        # PIERNA (25)
        ('Sentadilla Trasera con Barra', 'Pierna'), ('Sentadilla Frontal con Barra', 'Pierna'),
        ('Sentadilla Hack en Máquina', 'Pierna'), ('Sentadilla Búlgara con Mancuerna', 'Pierna'),
        ('Prensa de Piernas 45º', 'Pierna'), ('Prensa de Piernas Horizontal', 'Pierna'),
        ('Extensiones de Cuádriceps', 'Pierna'), ('Curl Femoral Tumbado', 'Pierna'),
        ('Curl Femoral Sentado', 'Pierna'), ('Curl Femoral de Pie', 'Pierna'),
        ('Peso Muerto Rumano', 'Pierna'), ('Peso Muerto Piernas Rígidas', 'Pierna'),
        ('Zancadas (Lunges) con Mancuernas', 'Pierna'), ('Zancadas Caminando con Barra', 'Pierna'),
        ('Step-up con Mancuernas', 'Pierna'), ('Hip Thrust con Barra', 'Pierna'),
        ('Glute Bridge (Puente de Glúteo)', 'Pierna'), ('Patada de Glúteo en Polea', 'Pierna'),
        ('Abducción de Cadera en Máquina', 'Pierna'), ('Aducción de Cadera en Máquina', 'Pierna'),
        ('Elevación de Talones de Pie', 'Pierna'), ('Elevación de Talones Sentado', 'Pierna'),
        ('Prensa de Gemelos', 'Pierna'), ('Sentadilla Goblet', 'Pierna'),
        ('Aberturas de Pierna (Clamshells)', 'Pierna'),

        # HOMBRO (20)
        ('Press Militar con Barra de Pie', 'Hombro'), ('Press Militar con Mancuernas Sentado', 'Hombro'),
        ('Press Arnold', 'Hombro'), ('Elevaciones Laterales con Mancuernas', 'Hombro'),
        ('Elevaciones Laterales en Polea', 'Hombro'), ('Elevaciones Frontales con Barra', 'Hombro'),
        ('Elevaciones Frontales con Mancuernas', 'Hombro'), ('Pájaros (Hombro Posterior)', 'Hombro'),
        ('Face Pull para Deltoide Posterior', 'Hombro'), ('Remo al Mentón con Barra', 'Hombro'),
        ('Encogimientos de Hombros con Barra', 'Hombro'), ('Encogimientos con Mancuernas', 'Hombro'),
        ('Press en Máquina de Hombros', 'Hombro'), ('Elevación Lateral en Máquina', 'Hombro'),
        ('Cruces Polea para Hombro Posterior', 'Hombro'), ('Press Militar en Multipower', 'Hombro'),
        ('Wall Walks', 'Hombro'), ('Handstand Pushups', 'Hombro'),
        ('Vueltas al Mundo con Disco', 'Hombro'), ('Elevación Frontal con Disco', 'Hombro'),

        # BICEPS (18)
        ('Curl de Bíceps con Barra Recta', 'Bíceps'), ('Curl de Bíceps con Barra Z', 'Bíceps'),
        ('Curl de Bíceps con Mancuernas (Supinado)', 'Bíceps'), ('Curl Martillo con Mancuernas', 'Bíceps'),
        ('Curl Predicador (Banco Scott) con Barra Z', 'Bíceps'), ('Curl de Bíceps Concentrado', 'Bíceps'),
        ('Curl de Bíceps en Polea Baja', 'Bíceps'), ('Curl de Bíceps en Polea Alta (Doble)', 'Bíceps'),
        ('Curl Inclinado con Mancuernas', 'Bíceps'), ('Curl de Bíceps Tipo Araña (Spider)', 'Bíceps'),
        ('Curl de Bíceps con Agarre Inverso', 'Bíceps'), ('Curl Martillo en Polea con Cuerda', 'Bíceps'),
        ('Curl de Bíceps en TRX', 'Bíceps'), ('Zottman Curl', 'Bíceps'),
        ('Drag Curl', 'Bíceps'), ('Curl de Bíceps en Máquina', 'Bíceps'),
        ('Curl de Bíceps Landmine', 'Bíceps'), ('21s (Curl de Bíceps)', 'Bíceps'),

        # TRICEPS (18)
        ('Press Francés con Barra Z', 'Tríceps'), ('Extensión de Tríceps tras Nuca con Mancuerna', 'Tríceps'),
        ('Extensiones en Polea Alta con Cuerda', 'Tríceps'), ('Extensiones en Polea Alta con Barra Recta', 'Tríceps'),
        ('Extensiones en Polea Alta con Barra V', 'Tríceps'), ('Patada de Tríceps con Mancuerna', 'Tríceps'),
        ('Fondos en Paralelas (Enfoque Tríceps)', 'Tríceps'), ('Fondos entre Bancos (Dips)', 'Tríceps'),
        ('Press de Banca Agarre Cerrado', 'Tríceps'), ('Extensión tras Nuca en Polea', 'Tríceps'),
        ('Extensiones de Tríceps en TRX', 'Tríceps'), ('Flexiones de Brazos Diamante', 'Tríceps'),
        ('Press Francés con Mancuernas', 'Tríceps'), ('Patada de Tríceps en Polea', 'Tríceps'),
        ('Tate Press', 'Tríceps'), ('Skullcrushers', 'Tríceps'),
        ('Extensiones de Tríceps un brazo en polea', 'Tríceps'), ('Press Californiano', 'Tríceps'),

        # CORE (15)
        ('Crunch Abdominal con Cuerda en Polea', 'Core'), ('Elevación de Piernas Colgado', 'Core'),
        ('Plancha Isométrica (Plank)', 'Core'), ('Rueda Abdominal (Ab Wheel)', 'Core'),
        ('Russian Twists', 'Core'), ('Woodchoppers en Polea', 'Core'),
        ('Bicycle Crunches', 'Core'), ('Deadbug', 'Core'),
        ('Bird Dog', 'Core'), ('L-Sit', 'Core'),
        ('Hollow Body Hold', 'Core'), ('Leg Raises en Suelo', 'Core'),
        ('Mountain Climbers', 'Core'), ('Side Plank (Plancha Lateral)', 'Core'),
        ('V-Ups', 'Core')
    ]

    # --- FOODS (~200 total) ---
    foods = [
        # PROTEINAS (50)
        ('Pechuga de Pollo', 'Proteínas', 165, 31, 0, 3.6),
        ('Contramuslo de Pollo', 'Proteínas', 209, 26, 0, 11),
        ('Muslo de Pollo', 'Proteínas', 174, 19, 0, 10),
        ('Ala de Pollo', 'Proteínas', 203, 30, 0, 8),
        ('Lomo de Cerdo', 'Proteínas', 242, 27, 0, 14),
        ('Solomillo de Cerdo', 'Proteínas', 143, 26, 0, 3.5),
        ('Filete de Ternera (Magra)', 'Proteínas', 172, 28, 0, 6),
        ('Ternera Picada (5% grasa)', 'Proteínas', 137, 21, 0, 5),
        ('Ternera Picada (15% grasa)', 'Proteínas', 241, 19, 0, 18),
        ('Solomillo de Ternera', 'Proteínas', 158, 27, 0, 5),
        ('Huevo Entero (L)', 'Proteínas', 155, 13, 1.1, 11),
        ('Clara de Huevo', 'Proteínas', 52, 11, 0.7, 0.2),
        ('Pavo (Pechuga)', 'Proteínas', 135, 30, 0, 1),
        ('Fiambre de Pavo (+90% carne)', 'Proteínas', 90, 18, 1, 1.5),
        ('Salmón Fresco', 'Proteínas', 208, 20, 0, 13),
        ('Atún al Natural (Lata)', 'Proteínas', 116, 26, 0, 1),
        ('Atún en Aceite (Escurrido)', 'Proteínas', 198, 24, 0, 11),
        ('Bacalao Fresco', 'Proteínas', 82, 18, 0, 0.7),
        ('Merluza Fresca', 'Proteínas', 78, 17, 0, 0.8),
        ('Lubina', 'Proteínas', 97, 18.5, 0, 2.5),
        ('Dorada', 'Proteínas', 115, 19, 0, 4),
        ('Sardina en Conserva', 'Proteínas', 208, 25, 0, 11),
        ('Gambas/Langostinos', 'Proteínas', 99, 24, 0, 0.3),
        ('Calamares', 'Proteínas', 92, 18, 3, 1.4),
        ('Pulpo Cocido', 'Proteínas', 164, 30, 4, 2),
        ('Mejillones al Vapor', 'Proteínas', 172, 24, 7, 4.5),
        ('Tofu Firme', 'Proteínas', 144, 15, 4, 8),
        ('Tempeh', 'Proteínas', 193, 19, 9, 11),
        ('Seitán', 'Proteínas', 370, 75, 14, 2),
        ('Heura (Bocados Originales)', 'Proteínas', 126, 18, 0.7, 3),
        ('Lomo Embuchado', 'Proteínas', 210, 32, 1, 8),
        ('Jamón Serrano (Magro)', 'Proteínas', 242, 30, 0, 13),
        ('Jamón York (Calidad)', 'Proteínas', 105, 18, 2, 3),
        ('Proteína de Suero (Whey isolated)', 'Proteínas', 370, 85, 2, 1),
        ('Proteína Vegana (Guisante/Arroz)', 'Proteínas', 380, 78, 5, 4),
        ('Caseína', 'Proteínas', 360, 80, 3, 2),
        ('Conejo (Carne)', 'Proteínas', 136, 22, 0, 5),
        ('Cangrejo (Surimi)', 'Proteínas', 95, 8, 15, 0.5),
        ('Chuleta de Cordero', 'Proteínas', 290, 25, 0, 21),
        ('Hígado de Pollo', 'Proteínas', 167, 24, 1, 5),
        ('Hígado de Ternera', 'Proteínas', 135, 20, 4, 4),
        ('Proteína de Soja Texturizada', 'Proteínas', 345, 52, 15, 1),
        ('Edamame (Sojas verdes)', 'Proteínas', 122, 11, 10, 5),
        ('Gelatina 0% (Polvo)', 'Proteínas', 340, 84, 0, 0),
        ('Caballa', 'Proteínas', 205, 19, 0, 14),
        ('Carne de Potón', 'Proteínas', 80, 15, 0, 1),
        ('Sardina Fresca', 'Proteínas', 153, 20, 0, 8),
        ('Solomillo de Pavo', 'Proteínas', 110, 24, 0, 1.5),
        ('Panto (Pescado)', 'Proteínas', 100, 20, 0, 2),
        ('Trucha', 'Proteínas', 141, 21, 0, 6),

        # HIDRATOS (50)
        ('Arroz Blanco (Grano Largo)', 'Hidratos', 360, 7, 79, 0.6),
        ('Arroz Integral', 'Hidratos', 350, 8, 73, 2.5),
        ('Arroz Basmati', 'Hidratos', 355, 8.5, 77, 0.5),
        ('Arroz de Sushi', 'Hidratos', 360, 6, 80, 0.5),
        ('Avena en Copos', 'Hidratos', 380, 13.5, 60, 7),
        ('Harina de Avena', 'Hidratos', 370, 11, 62, 6),
        ('Quinoa Seca', 'Hidratos', 368, 14, 64, 6),
        ('Pasta de Trigo (Seca)', 'Hidratos', 350, 12, 70, 1.5),
        ('Pasta Integral (Seca)', 'Hidratos', 340, 13, 65, 2.5),
        ('Pasta de Trigo Sarraceno', 'Hidratos', 343, 13, 71, 3.4),
        ('Couscous Seco', 'Hidratos', 376, 12.8, 77, 0.6),
        ('Patata Fresca', 'Hidratos', 77, 2, 17, 0.1),
        ('Boniato / Batata', 'Hidratos', 86, 1.6, 20, 0.1),
        ('Yuca', 'Hidratos', 160, 1.4, 38, 0.3),
        ('Garbanzos Secos', 'Hidratos', 364, 19, 60, 6),
        ('Lentejas Secas', 'Hidratos', 352, 25, 63, 1),
        ('Judías Blancas Secas', 'Hidratos', 333, 23, 60, 0.8),
        ('Guisantes Frescos', 'Hidratos', 81, 5, 14, 0.4),
        ('Pan Integral de Centeno', 'Hidratos', 259, 8.5, 48, 3.3),
        ('Pan de Molde Integral', 'Hidratos', 250, 9, 45, 3),
        ('Pan Wasa / Knäckebröd', 'Hidratos', 330, 10, 60, 1.5),
        ('Tortitas de Arroz', 'Hidratos', 387, 8, 80, 3),
        ('Tortitas de Maíz', 'Hidratos', 385, 7, 85, 1),
        ('Tortillas de Maíz (Mexicanas)', 'Hidratos', 218, 5.7, 45, 2.8),
        ('Tortillas de Trigo', 'Hidratos', 310, 8, 50, 8),
        ('Muesli (Sin Azúcar)', 'Hidratos', 370, 10, 65, 6),
        ('Cereal Corn Flakes', 'Hidratos', 360, 7, 84, 0.5),
        ('Dátiles', 'Hidratos', 280, 2, 75, 0.4),
        ('Pasas', 'Hidratos', 299, 3, 79, 0.5),
        ('Miel de Abeja', 'Hidratos', 304, 0.3, 82, 0),
        ('Azúcar Moreno', 'Hidratos', 380, 0, 98, 0),
        ('Cebada Perla', 'Hidratos', 352, 10, 77, 1.2),
        ('Mijo', 'Hidratos', 378, 11, 73, 4.2),
        ('Espelta en Grano', 'Hidratos', 338, 15, 70, 2.4),
        ('Sémola de Trigo', 'Hidratos', 360, 12.7, 73, 1),
        ('Pasta de Lenteja Roja', 'Hidratos', 340, 25, 52, 1.5),
        ('Gnocchi de Patata', 'Hidratos', 150, 3.5, 33, 0.5),
        ('Salvado de Avena', 'Hidratos', 246, 17, 66, 7),
        ('Germen de Trigo', 'Hidratos', 360, 23, 52, 10),
        ('Harina de Maíz', 'Hidratos', 365, 8, 77, 3.5),
        ('Galletas de Avena (Caseras)', 'Hidratos', 450, 8, 65, 18),
        ('Castañas', 'Hidratos', 196, 1.6, 44, 1.2),
        ('Calabaza Cocida', 'Hidratos', 26, 1, 6.5, 0.1),
        ('Remolacha Cocida', 'Hidratos', 43, 1.6, 10, 0.2),
        ('Zanahoria Cruda', 'Hidratos', 41, 0.9, 10, 0.2),
        ('Chirivía', 'Hidratos', 75, 1.2, 18, 0.3),
        ('Maíz Dulce (Lata)', 'Hidratos', 86, 3, 19, 1.2),
        ('Gofio Canario', 'Hidratos', 370, 11, 72, 3),
        ('Biscote de Trigo', 'Hidratos', 390, 11, 75, 4),
        ('Harina de Trigo Todo Uso', 'Hidratos', 364, 10, 76, 1),

        # GRASAS (35)
        ('Aceite de Oliva Virgen Extra', 'Grasas', 884, 0, 0, 100),
        ('Aceite de Coco', 'Grasas', 862, 0, 0, 100),
        ('Aceite de Girasol', 'Grasas', 884, 0, 0, 100),
        ('Aceite de Lino', 'Grasas', 884, 0, 0, 100),
        ('Mantequilla (Sin Sal)', 'Grasas', 717, 0.8, 0, 81),
        ('Ghee (Mantequilla Clarificada)', 'Grasas', 900, 0, 0, 100),
        ('Aguacate', 'Grasas', 160, 2, 8.5, 15),
        ('Nueces (Peladas)', 'Grasas', 654, 15, 14, 65),
        ('Almendras (Naturales)', 'Grasas', 579, 21, 22, 50),
        ('Avellanas', 'Grasas', 628, 15, 17, 61),
        ('Anacardos (Naturales)', 'Grasas', 553, 18, 30, 44),
        ('Pistachos', 'Grasas', 562, 20, 28, 45),
        ('Cacahuetes (Naturales)', 'Grasas', 567, 26, 16, 49),
        ('Semillas de Chía', 'Grasas', 486, 16, 42, 31),
        ('Semillas de Calabaza', 'Grasas', 559, 30, 11, 49),
        ('Semillas de Girasol', 'Grasas', 584, 21, 20, 51),
        ('Semillas de Sésamo', 'Grasas', 573, 18, 23, 50),
        ('Mantequilla de Cacahuete (100%)', 'Grasas', 588, 25, 20, 50),
        ('Crema de Almendras (100%)', 'Grasas', 614, 21, 10, 55),
        ('Tahini (Crema de Sésamo)', 'Grasas', 595, 17, 21, 54),
        ('Olivas Verdes', 'Grasas', 145, 1, 4, 15),
        ('Olivas Negras', 'Grasas', 115, 0.8, 6, 11),
        ('Coco Rallado (Seco)', 'Grasas', 660, 7, 24, 65),
        ('Chocolate Negro 85%', 'Grasas', 598, 8, 15, 50),
        ('Chocolate Negro 99%', 'Grasas', 620, 12, 8, 55),
        ('Yema de Huevo', 'Grasas', 322, 16, 3.6, 27),
        ('Pesto Genovés', 'Grasas', 450, 5, 6, 45),
        ('Mayonesa Real', 'Grasas', 680, 1, 1, 75),
        ('Piñones', 'Grasas', 673, 14, 13, 68),
        ('Nueces del Brasil', 'Grasas', 656, 14, 12, 66),
        ('Nueces de Macadamia', 'Grasas', 718, 8, 14, 76),
        ('Manteca de Cerdo', 'Grasas', 900, 0, 0, 100),
        ('Semillas de Cáñamo', 'Grasas', 553, 31, 9, 49),
        ('Aceite de Aguacate', 'Grasas', 884, 0, 0, 100),
        ('Pecanas', 'Grasas', 691, 9, 14, 72),

        # VERDURAS (35)
        ('Brócoli', 'Verduras', 34, 2.8, 6.6, 0.4),
        ('Espinacas Frescas', 'Verduras', 23, 2.9, 3.6, 0.4),
        ('Espárragos Trigueros', 'Verduras', 20, 2.2, 3.9, 0.1),
        ('Judías Verdes', 'Verduras', 31, 1.8, 7, 0.2),
        ('Calabacín', 'Verduras', 17, 1.2, 3.1, 0.3),
        ('Berenjena', 'Verduras', 25, 1, 5.9, 0.2),
        ('Pimiento Rojo', 'Verduras', 31, 1, 6, 0.3),
        ('Pimiento Verde', 'Verduras', 20, 0.9, 4.6, 0.2),
        ('Pimiento Amarillo', 'Verduras', 27, 1, 6.3, 0.2),
        ('Cebolla', 'Verduras', 40, 1.1, 9.3, 0.1),
        ('Cebolla Roja', 'Verduras', 42, 1.2, 10, 0.1),
        ('Tomate Cherry', 'Verduras', 18, 0.9, 3.9, 0.2),
        ('Tomate de Ensalada', 'Verduras', 18, 0.9, 3.9, 0.2),
        ('Pepino', 'Verduras', 15, 0.6, 3.6, 0.1),
        ('Lechuga Iceberg', 'Verduras', 14, 0.9, 3, 0.1),
        ('Lechuga Romana', 'Verduras', 17, 1.2, 3.3, 0.3),
        ('Canónigos', 'Verduras', 21, 2, 3.6, 0.4),
        ('Rúcula', 'Verduras', 25, 2.6, 3.7, 0.7),
        ('Champiñones', 'Verduras', 22, 3.1, 3.3, 0.3),
        ('Setas Shiitake', 'Verduras', 34, 2.2, 6.8, 0.5),
        ('Coliflor', 'Verduras', 25, 1.9, 5, 0.3),
        ('Repollo / Col', 'Verduras', 25, 1.3, 5.8, 0.1),
        ('Col de Bruselas', 'Verduras', 43, 3.4, 9, 0.3),
        ('Lombarda', 'Verduras', 31, 1.4, 7, 0.2),
        ('Alcachofa', 'Verduras', 47, 3.3, 10, 0.2),
        ('Apio', 'Verduras', 16, 0.7, 3, 0.2),
        ('Puerro', 'Verduras', 61, 1.5, 14, 0.3),
        ('Ajo', 'Verduras', 149, 6.4, 33, 0.5),
        ('Rábano', 'Verduras', 16, 0.7, 3.4, 0.1),
        ('Bambú (Brotes)', 'Verduras', 27, 2.6, 5, 0.3),
        ('Germinados de Alfalfa', 'Verduras', 23, 4, 2, 0.7),
        ('Endivia', 'Verduras', 17, 1.2, 3.3, 0.2),
        ('Hinojo', 'Verduras', 31, 1.2, 7, 0.2),
        ('Kale (Col Rizada)', 'Verduras', 49, 4.3, 8.8, 0.9),
        ('Bimi', 'Verduras', 35, 3.5, 5, 0.5),

        # FRUTAS (30)
        ('Manzana Royal', 'Frutas', 52, 0.3, 14, 0.2),
        ('Plátano (Canarias)', 'Frutas', 89, 1.1, 23, 0.3),
        ('Pera Conference', 'Frutas', 57, 0.4, 15, 0.1),
        ('Naranja', 'Frutas', 47, 0.9, 12, 0.1),
        ('Mandarina', 'Frutas', 53, 0.8, 13, 0.3),
        ('Fresas', 'Frutas', 32, 0.7, 7.7, 0.3),
        ('Arándanos Azules', 'Frutas', 57, 0.7, 14, 0.3),
        ('Frambuesas', 'Frutas', 52, 1.2, 12, 0.6),
        ('Moras', 'Frutas', 43, 1.4, 10, 0.5),
        ('Piña Natural', 'Frutas', 50, 0.5, 13, 0.1),
        ('Kiwi Zespri', 'Frutas', 61, 1.1, 15, 0.5),
        ('Mango', 'Frutas', 60, 0.8, 15, 0.4),
        ('Sandía', 'Frutas', 30, 0.6, 7.6, 0.2),
        ('Melón Cantalupo', 'Frutas', 34, 0.8, 8, 0.2),
        ('Uva Blanca', 'Frutas', 67, 0.6, 17, 0.4),
        ('Uva Negra', 'Frutas', 69, 0.7, 18, 0.2),
        ('Ciruela Roja', 'Frutas', 46, 0.7, 11, 0.3),
        ('Melocotón / Durazno', 'Frutas', 39, 0.9, 10, 0.3),
        ('Nectarina', 'Frutas', 44, 1.1, 11, 0.3),
        ('Albaricoque', 'Frutas', 48, 1.4, 11, 0.4),
        ('Cerezas', 'Frutas', 63, 1.1, 16, 0.2),
        ('Higos Frescos', 'Frutas', 74, 0.8, 19, 0.3),
        ('Granada', 'Frutas', 83, 1.7, 19, 1.2),
        ('Papaya', 'Frutas', 43, 0.5, 11, 0.3),
        ('Chirimoya', 'Frutas', 75, 1.6, 18, 0.7),
        ('Pomelo / Toronja', 'Frutas', 42, 0.8, 11, 0.1),
        ('Limón', 'Frutas', 29, 1.1, 9, 0.3),
        ('Coco Fresco', 'Frutas', 354, 3.3, 15, 33),
        ('Caqui / Persimon', 'Frutas', 70, 0.6, 18, 0.2),
        ('Maracuyá', 'Frutas', 97, 2.2, 23, 0.7)
    ]

    # Delete olds to avoid duplicates in this specific expansion
    c.execute("DELETE FROM exercises")
    c.execute("DELETE FROM foods")

    c.executemany("INSERT INTO exercises (name, muscle_group) VALUES (?, ?)", exercises)
    c.executemany("INSERT INTO foods (name, category, kcal, protein, carbs, fat) VALUES (?, ?, ?, ?, ?, ?)", foods)

    print(f"Dataset expandido: {len(exercises)} ejercicios y {len(foods)} alimentos.")

    conn.commit()
    conn.close()

if __name__ == "__main__":
    expand()
